
#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
<<<<<<<< HEAD:drivers/soc/mediatek/devapc/mt6761/Makefile
========
obj-y += ov50d40_truly_main_i_mipi_raw.o
>>>>>>>> 87a2be8e37f6 (gale: drivers: misc: mediatek: imgsensor: Import Xiaomi changes):drivers/misc/mediatek/imgsensor/src/common/v1_factory/ov50d40_truly_main_i_mipi_raw/Makefile

obj-y += devapc.o